{% set name = "prismatools" %}
{% set version = "0.1.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prismatools-{{ version }}.tar.gz
  sha256: 3e8014a8877192a339651b748e37a8849784db6268eac6cad7462b20eba5f669

build:
  noarch: python
  entry_points:
    - prismatools=prismatools.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - affine
    - bqplot
    - h5py
    - ipyevents
    - ipyfilechooser
    - ipyleaflet
    - ipywidgets
    - leafmap
    - localtileserver
    - numpy
    - rioxarray
    - scikit-learn
    - xarray

test:
  imports:
    - prismatools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gthlor/prismatools
  summary: prismatools is an open-source Python package for reading, analyzing, and visualizing hyperspectral imagery from the PRISMA mission.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gthlor
